for i in range(11):
    print(1 * i)
    print(2 * i)
    print(3 * i)
    print(4 * i)
    print(5 * i)
    print(6 * i)
    print(7 * i)
    print(8 * i)
    print(9 * i)
    print(10 * i)